
v_max1f     =     	parameters(1);	%	nmol/ (10^6 cells)/day
Ki_1        =     	parameters(2);	%	mM
Km_1        =     	parameters(3);	%	mM
exp_1a     	=     	parameters(4);	%	Unitless
exp_1b     	=     	parameters(5);	%	Unitless
TC_1b     	=     	parameters(6);	%	Unitless
v_max2     	=     	parameters(7);	%	nmol/ (10^6 cells)/day
Km_2        =     	parameters(8);	%	mM
v_max3f     =     	parameters(9);	%	nmol/ (10^6 cells)/day
v_max3r     =     	parameters(10);	%	nmol/ (10^6 cells)/day
Km_3a     	=       parameters(11);	%	mM
Km_3b     	=     	parameters(12);	%	mM
Km_3c     	=     	parameters(13);	%	mM
TC_3b     	=     	parameters(14);	%	Unitless
v_max8f     =     	parameters(15);	%	nmol/ (10^6 cells)/day
v_max8r     =     	parameters(16);	%	nmol/ (10^6 cells)/day
Km_8a     	=     	parameters(17);	%	mM
Km_8b     	=       parameters(18);	%	mM
Km_8c     	=     	parameters(19);	%	mM
TC_8b     	=     	parameters(20);	%	Unitless
v_max9f     =     	parameters(21);	%	nmol/ (10^6 cells)/day
v_max9r     =     	parameters(22);	%	nmol/ (10^6 cells)/day
Km_9        =     	parameters(23);	%	mM
v_max10f    =     	parameters(24);	%	nmol/ (10^6 cells)/day
v_max10r    =     	parameters(25);	%	nmol/ (10^6 cells)/day
Km_10a     	=     	parameters(26);	%	mM
Km_10b     	=     	parameters(27);	%	mM
Km_10c     	=     	parameters(28);	%	mM
TC_10b     	=     	parameters(29);	%	Unitless
v_max11     =     	parameters(30);	%	nmol/ (10^6 cells)/day
v_max12f    =     	parameters(31);	%	nmol/ (10^6 cells)/day
v_max12r    =     	parameters(32);	%	nmol/ (10^6 cells)/day
Km_12a     	=     	parameters(33);	%	mM
Km_12b     	=     	parameters(34);	%	mM
v_max13    	=     	parameters(35);	%	nmol/ (10^6 cells)/day
Km_13     	=     	parameters(36);	%	mM
v_max16     =     	parameters(37);	%	nmol/ (10^6 cells)/day
Km_16a     	=     	parameters(38);	%	mM
Km_16b     	=     	parameters(39);	%	mM
Km_16c     	=     	parameters(40);	%	mM
TC_16b     	=     	parameters(41);	%	Unitless
v_max17     =     	parameters(42);	%	nmol/ (10^6 cells)/day
Ki_17     	=     	parameters(43);	%	mM
exp_17a     =     	parameters(44);	%	Unitless
exp_17b     =     	parameters(45);	%	Unitless
v_max33a    =     	parameters(46);	%	nmol/ (10^6 cells)/day
v_max33b    =     	parameters(47);	%	nmol/ (10^6 cells)/day
